openapi: 3.0.1
info:
  title: Pod Nug
  description: A plugin for summarizing youtube podcasts provided by the user, allowing them to prompt it with questions and discover the key episode insights. 
  version: "v1"
servers:
  - url: http://localhost:5003
paths:
  /podcasts:
    get:
      operationId: getPodcast
      summary: Get the podcast
      description: Get the podcast
      parameters:
        - in: query
          name: podcast
          schema:
            type: string
          description: podcast
        - in: query
          name: prompt
          schema:
            type: string
          description: user prompt
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
# openapi: 3.0.1
# info:
#   title: Pod Nug
#   description: A plugin for summarizing youtube podcasts provided by the user, allowing them to prompt it with questions and discover the key episode insights. 
#   version: 'v1'
# servers:
#   - url: http://localhost:5003
# paths:
#   /podcasts/{podcast}:
#     get:
#       operationId: getPodcast
#       summary: Get the podcast
#       parameters:
#       - in: path
#         name: podcast
#         schema:
#             type: url
#         required: true
#         description: The name of the podcast
#       responses:
#         "200":
#           description: OK
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/getPodcastResponse'
# components:
#   schemas:
#     getPodcastResponse:
#       type: object
#       properties:
#         podcast:
#           type: string
#           description: the transcript of the podcast to return